package io.github.foodjournal.application;
import io.github.foodjournal.config.BotProperties; import io.github.foodjournal.domain.*; import io.github.foodjournal.repository.*; import java.math.BigDecimal; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class JournalApplicationService {
 private final FoodUserRepository users; private final UserSettingsRepository settings; private final FoodEntryRepository entries; private final FoodItemRepository items; private final IntentInterpreter interpreter; private final BotProperties props;
 public JournalApplicationService(FoodUserRepository u,UserSettingsRepository s,FoodEntryRepository e,FoodItemRepository itemRepository,IntentInterpreter i,BotProperties p){users=u;settings=s;entries=e;items=itemRepository;interpreter=i;props=p;}
 @Transactional public String handle(long telegramUserId,String displayName,String message){ FoodUser user=users.findByTelegramUserId(telegramUserId).orElseGet(()->{FoodUser created=users.save(new FoodUser(telegramUserId,displayName));settings.save(new UserSettings(created,props.defaultTimezone()));return created;}); if(message.startsWith("/"))return command(user,message); JournalIntent intent=interpreter.interpret(message); return execute(user,intent,message); }
 private String command(FoodUser user,String command){ if(command.equals("/start")||command.equals("/help"))return "Send a meal in English or Romanian. Use /today, /report, or /settings."; if(command.equals("/today")||command.equals("/report"))return today(user); if(command.equals("/settings"))return "Say: set timezone to Europe/Bucharest, set target to 2200 calories, or turn reports off."; return "Unknown command. Use /help."; }
 private String execute(FoodUser user,JournalIntent i,String raw){ if(i==null||i.type()==null)return "I could not understand that safely. Please rephrase."; return switch(i.type()){ case LOG_MEAL -> log(user,i,raw); case QUERY_JOURNAL -> query(user,i); case EDIT_ENTRY -> edit(user,i); case DELETE_ENTRY -> delete(user,i); case UPDATE_SETTINGS -> configure(user,i); case CHAT -> "I can log meals, show your journal, update settings, or help with a previous entry."; }; }
 private String log(FoodUser user,JournalIntent i,String raw){ if(i.mealDescription()==null||i.mealDescription().isBlank())return "Tell me what you ate or drank."; if(i.calories()!=null&&(i.calories()<0||i.calories()>10000))return "That calorie value is not valid."; if(i.items()!=null&&i.items().stream().anyMatch(item->item.name()==null||item.name().isBlank()||item.grams()!=null&&item.grams()<=0||item.calories()!=null&&(item.calories()<0||item.calories()>10000)))return "One or more meal items are not valid."; FoodEntry e=entries.save(new FoodEntry(user,i.mealDescription(),Instant.now(),i.calories(),i.calories()==null?"manual":"ai_estimate",i.calories()==null?"unknown":"estimate")); if(i.items()!=null) for(JournalIntent.MealItem item:i.items()) items.save(new FoodItem(e,item.name(),item.grams()==null?null:BigDecimal.valueOf(item.grams()),item.calories())); return "Logged: "+i.mealDescription()+" (entry #"+e.getId()+")."; }
 private String query(FoodUser user,JournalIntent i){String term=i.query(); List<FoodEntry> found=(term==null||term.isBlank())?todayEntries(user):entries.searchByUserAndTerm(user,term); if(found.isEmpty())return "No matching entries found."; return found.stream().limit(10).map(e->"#"+e.getId()+" "+e.getOriginalMessage()+(e.getCalories()==null?"":" — "+e.getCalories()+" kcal")).reduce("Entries:\n",(a,b)->a+b+"\n");}
 private String edit(FoodUser user,JournalIntent i){if(i.entryId()==null)return "Tell me the entry number to change."; return entries.findByIdAndUser(i.entryId(),user).map(e->{if(i.mealDescription()==null||i.mealDescription().isBlank())return "Tell me the corrected meal description.";if(i.calories()!=null&&(i.calories()<0||i.calories()>10000))return "That calorie value is not valid.";e.revise(i.mealDescription(),i.calories());return "Updated entry #"+e.getId()+".";}).orElse("I could not find that entry.");}
 private String delete(FoodUser user,JournalIntent i){if(i.entryId()==null)return "Tell me the entry number to delete.";return entries.findByIdAndUser(i.entryId(),user).map(e->{entries.delete(e);return "Deleted entry #"+i.entryId()+".";}).orElse("I could not find that entry.");}
 private String configure(FoodUser user,JournalIntent i){UserSettings s=settings.findById(user.getId()).orElseThrow();if(i.timezone()!=null){try{ZoneId.of(i.timezone());s.setTimezone(i.timezone());}catch(Exception e){return "That is not a valid IANA timezone.";}}if(i.calorieTarget()!=null){if(i.calorieTarget()<1200||i.calorieTarget()>5000)return "Your daily target must be between 1200 and 5000 kcal.";s.setCalorieTarget(i.calorieTarget());}return "Settings updated.";}
 private String today(FoodUser user){List<FoodEntry> rows=todayEntries(user);int calories=rows.stream().map(FoodEntry::getCalories).filter(Objects::nonNull).mapToInt(Integer::intValue).sum();return "Today: "+rows.size()+" entries, "+calories+" kcal logged.";}
 private List<FoodEntry> todayEntries(FoodUser user){ZoneId zone=ZoneId.of(settings.findById(user.getId()).map(UserSettings::getTimezone).orElse("Europe/Bucharest"));LocalDate day=LocalDate.now(zone);return entries.findByUserAndEatenAtBetweenOrderByEatenAtAsc(user,day.atStartOfDay(zone).toInstant(),day.plusDays(1).atStartOfDay(zone).toInstant());}
}
