package io.github.foodjournal.application;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.foodjournal.domain.*;
import io.github.foodjournal.repository.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.interceptor.TransactionAspectSupport;

@Service
public class JournalToolExecutor {
  private final ObjectMapper json; private final UserSettingsRepository settings; private final FoodEntryRepository entries;
  private final FoodItemRepository items; private final PrivateFoodRepository privateFoods; private final NutritionResolver nutrition;
  private final DailyStatusService dailyStatus; private final PendingAgentActionRepository pending;
  public JournalToolExecutor(ObjectMapper json, UserSettingsRepository settings, FoodEntryRepository entries, FoodItemRepository items, PrivateFoodRepository privateFoods, NutritionResolver nutrition, DailyStatusService dailyStatus, PendingAgentActionRepository pending) { this.json=json;this.settings=settings;this.entries=entries;this.items=items;this.privateFoods=privateFoods;this.nutrition=nutrition;this.dailyStatus=dailyStatus;this.pending=pending; }

  @Transactional public AgentToolResult execute(AgentContext c, JournalAgentModel.ToolCall call, List<String> todos) {
    try { Map<String,Object> a=json.readValue(call.arguments()==null?"{}":call.arguments(),new TypeReference<>(){}); return switch(call.name()) {
      case "get_today_summary" -> today(c); case "search_entries" -> search(c,a); case "get_entry" -> entry(c,a);
      case "get_settings" -> settings(c); case "resolve_nutrition", "lookup_food" -> resolve(c,a); case "get_private_food" -> privateFood(c,a);
      case "plan_todos" -> planTodos(a,todos); case "complete_todo" -> completeTodo(a,todos);
      case "create_food_entry" -> create(c,a); case "save_private_food" -> savePrivate(c,a); case "update_settings" -> updateSettings(c,a);
      case "prepare_entry_edit" -> prepare(c,a,"EDIT"); case "prepare_entry_delete" -> prepare(c,a,"DELETE");
      case "get_pending_action" -> getPending(c); case "confirm_pending_action" -> confirm(c); default -> AgentToolResult.failure("VALIDATION_ERROR","That tool is not available.");
    }; } catch (IllegalArgumentException e) { TransactionAspectSupport.currentTransactionStatus().setRollbackOnly(); return AgentToolResult.failure("VALIDATION_ERROR", "The supplied details are invalid."); }
      catch (Exception e) { TransactionAspectSupport.currentTransactionStatus().setRollbackOnly(); return AgentToolResult.failure("TEMPORARY_FAILURE", "That operation could not be completed now."); }
  }
  private AgentToolResult planTodos(Map<String,Object>a,List<String> todos){Object raw=a.get("todos");if(!(raw instanceof List<?> list))return AgentToolResult.failure("VALIDATION_ERROR","Provide a short todo list.");todos.clear();for(Object value:list){if(value!=null&&!String.valueOf(value).isBlank()&&todos.size()<6)todos.add(String.valueOf(value));}return AgentToolResult.ok(Map.of("todos",List.copyOf(todos)));}
  private AgentToolResult completeTodo(Map<String,Object>a,List<String> todos){String todo=str(a,"todo");if(todo==null||!todos.remove(todo))return AgentToolResult.failure("NOT_FOUND","That todo is not in the current run.");return AgentToolResult.ok(Map.of("todos",List.copyOf(todos)));}
  private AgentToolResult today(AgentContext c){ List<FoodEntry> rows=forToday(c.user()); int total=rows.stream().map(FoodEntry::getCalories).filter(Objects::nonNull).mapToInt(Integer::intValue).sum(); Integer target=profile(c).getCalorieTarget(); return AgentToolResult.ok(Map.of("calories",total,"entries",rows.size(),"target",target==null?"unset":target)); }
  private AgentToolResult search(AgentContext c,Map<String,Object>a){String q=str(a,"query"); List<FoodEntry> rows=q==null?forToday(c.user()):entries.searchByUserAndTerm(c.user(),q); return AgentToolResult.ok(Map.of("entries",rows.stream().limit(10).map(this::summary).toList()));}
  private AgentToolResult entry(AgentContext c,Map<String,Object>a){return entries.findByIdAndUser(number(a,"entryId").longValue(),c.user()).<AgentToolResult>map(e->AgentToolResult.ok(Map.of("entry",summary(e)))).orElse(AgentToolResult.failure("NOT_FOUND","No matching journal entry exists."));}
  private AgentToolResult settings(AgentContext c){UserSettings s=profile(c);return AgentToolResult.ok(Map.of("timezone",s.getTimezone(),"calorieTarget",s.getCalorieTarget()==null?"unset":s.getCalorieTarget(),"reportsEnabled",s.isReportsEnabled()));}
  private AgentToolResult resolve(AgentContext c,Map<String,Object>a){JournalIntent.MealItem requested=mealItem(a); NutritionResolver.ResolvedMealItem r=nutrition.resolve(c.user(),requested); JournalIntent.MealItem i=r.item(); if(i==null||i.totalCalories()==null)return AgentToolResult.failure("NOT_FOUND","Nutrition could not be resolved; ask for calories or a barcode."); return AgentToolResult.ok(Map.of("name",i.name(),"grams",i.grams(),"totalCalories",i.totalCalories(),"caloriesPer100g",i.caloriesPer100g()==null?"unknown":i.caloriesPer100g(),"source",r.source()));}
  private AgentToolResult privateFood(AgentContext c,Map<String,Object>a){String name=str(a,"name");return privateFoods.findByUserAndNameIgnoreCase(c.user(),name).<AgentToolResult>map(p->AgentToolResult.ok(Map.of("name",p.getName(),"caloriesPer100g",p.getCaloriesPer100g()))).orElse(AgentToolResult.failure("NOT_FOUND","No household food matches that name."));}
  private AgentToolResult create(AgentContext c,Map<String,Object>a){List<Map<String,Object>> raw=json.convertValue(a.get("items"),new TypeReference<>(){});if(raw==null||raw.isEmpty())return AgentToolResult.failure("VALIDATION_ERROR","At least one food item is required.");List<NutritionResolver.ResolvedMealItem> resolved=new ArrayList<>();for(Map<String,Object> row:raw){JournalIntent.MealItem i=mealItem(row);if(i.name()==null||i.name().isBlank()||i.grams()==null||i.grams()<=0)return AgentToolResult.failure("VALIDATION_ERROR","Each item needs a name and a positive gram quantity.");NutritionResolver.ResolvedMealItem r=nutrition.resolve(c.user(),i);if(r.item()==null||r.item().totalCalories()==null)return AgentToolResult.failure("VALIDATION_ERROR","One item needs calories per 100 g, total calories, a barcode, or a saved household food.");resolved.add(r);}int total=resolved.stream().map(NutritionResolver.ResolvedMealItem::item).mapToInt(i->i.totalCalories()).sum();if(total<=0||total>10000)return AgentToolResult.failure("VALIDATION_ERROR","The meal calorie total is outside the allowed range.");FoodEntry saved=entries.save(new FoodEntry(c.user(),c.message(),Instant.now(),total,"mixed","high"));for(NutritionResolver.ResolvedMealItem r:resolved){JournalIntent.MealItem i=r.item();items.save(new FoodItem(saved,i.name(),BigDecimal.valueOf(i.grams()),i.totalCalories(),decimal(i.proteinGrams()),decimal(i.carbsGrams()),decimal(i.fatGrams()),r.source(),"high"));}dailyStatus.refresh(c.user(),c.chatId());return AgentToolResult.ok(Map.of("entry",summary(saved),"today",today(c).data()));}
  private AgentToolResult savePrivate(AgentContext c,Map<String,Object>a){String name=str(a,"name");Integer kcal=number(a,"caloriesPer100g");if(name==null||name.isBlank()||kcal<0||kcal>10000)return AgentToolResult.failure("VALIDATION_ERROR","A food name and valid calories per 100 g are required.");PrivateFood p=privateFoods.findByUserAndNameIgnoreCase(c.user(),name).orElse(null);if(p==null)privateFoods.save(new PrivateFood(c.user(),name,kcal,null,null,null));else p.refresh(kcal,null,null,null);return AgentToolResult.ok(Map.of("name",name,"caloriesPer100g",kcal));}
  private AgentToolResult updateSettings(AgentContext c,Map<String,Object>a){UserSettings s=profile(c);if(a.containsKey("timezone")){try{s.setTimezone(ZoneId.of(str(a,"timezone")).getId());}catch(Exception x){return AgentToolResult.failure("VALIDATION_ERROR","Use a valid IANA timezone.");}}if(a.containsKey("calorieTarget")){int target=number(a,"calorieTarget");if(target<1200||target>5000)return AgentToolResult.failure("VALIDATION_ERROR","The calorie target must be 1200–5000.");s.setCalorieTarget(target);}if(a.containsKey("reportsEnabled"))s.setReportsEnabled(Boolean.parseBoolean(String.valueOf(a.get("reportsEnabled"))));return settings(c);}
  private AgentToolResult prepare(AgentContext c,Map<String,Object>a,String type){Long id=number(a,"entryId").longValue();FoodEntry e=entries.findByIdAndUser(id,c.user()).orElse(null);if(e==null)return AgentToolResult.failure("NOT_FOUND","No matching journal entry exists.");pending.save(PendingAgentAction.forAction(c.user(),type,id,str(a,"description"),a.containsKey("calories")?number(a,"calories"):null,Instant.now()));return new AgentToolResult(false,"REQUIRES_CONFIRMATION",Map.of("entry",summary(e),"action",type),"Ask the user to explicitly confirm this change.");}
  private AgentToolResult getPending(AgentContext c){return pending.findByUserAndExpiresAtAfter(c.user(),Instant.now()).<AgentToolResult>map(p->AgentToolResult.ok(Map.of("action",p.getActionType(),"entryId",p.getEntryId(),"summary",p.getSummary()))).orElse(AgentToolResult.failure("NOT_FOUND","There is no pending change to confirm."));}
  private AgentToolResult confirm(AgentContext c){PendingAgentAction p=pending.findByUserAndExpiresAtAfter(c.user(),Instant.now()).orElse(null);if(p==null)return AgentToolResult.failure("NOT_FOUND","There is no pending change to confirm.");if(!isConfirmation(c.message())||!p.getCreatedAt().isBefore(c.startedAt()))return AgentToolResult.failure("REQUIRES_CONFIRMATION","Show the pending change and wait for a separate explicit confirmation.");FoodEntry e=entries.findByIdAndUser(p.getEntryId(),c.user()).orElse(null);if(e==null){pending.delete(p);return AgentToolResult.failure("NOT_FOUND","That journal entry no longer exists.");}if("DELETE".equals(p.getActionType()))entries.delete(e);else e.revise(p.getDescription(),p.getCalories());pending.delete(p);dailyStatus.refresh(c.user(),c.chatId());return AgentToolResult.ok(Map.of("action",p.getActionType(),"entryId",p.getEntryId()));}
  private UserSettings profile(AgentContext c){return settings.findById(c.user().getId()).orElseThrow();} private List<FoodEntry> forToday(FoodUser u){ZoneId z=ZoneId.of(settings.findById(u.getId()).orElseThrow().getTimezone());LocalDate d=LocalDate.now(z);return entries.findByUserAndEatenAtBetweenOrderByEatenAtAsc(u,d.atStartOfDay(z).toInstant(),d.plusDays(1).atStartOfDay(z).toInstant());} private Map<String,Object> summary(FoodEntry e){return Map.of("id",e.getId(),"calories",e.getCalories(),"eatenAt",e.getEatenAt().toString(),"description",e.getOriginalMessage());} private String str(Map<String,Object>a,String key){Object v=a.get(key);return v==null?null:String.valueOf(v);} private Integer number(Map<String,Object>a,String key){Object v=a.get(key);if(v==null)throw new IllegalArgumentException();return v instanceof Number n?n.intValue():Integer.parseInt(String.valueOf(v));} private JournalIntent.MealItem mealItem(Map<String,Object>a){return new JournalIntent.MealItem(str(a,"name"),a.get("grams")==null?null:Double.valueOf(String.valueOf(a.get("grams"))),a.get("totalCalories")==null?null:number(a,"totalCalories"),a.get("caloriesPer100g")==null?null:number(a,"caloriesPer100g"),null,null,null,str(a,"barcode"));} private BigDecimal decimal(Double v){return v==null?null:BigDecimal.valueOf(v);} private boolean isConfirmation(String message){String m=message==null?"":message.trim().toLowerCase(Locale.ROOT);return Set.of("da","confirm","confirmă","confirma","yes").contains(m);}
}
