package io.github.foodjournal.application;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.foodjournal.domain.*;
import io.github.foodjournal.repository.*;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.*;
import org.mockito.ArgumentCaptor;

class JournalToolExecutorEstimateTest {
  private final FoodEntryRepository entries=mock(FoodEntryRepository.class); private final FoodItemRepository items=mock(FoodItemRepository.class); private final UserSettingsRepository settings=mock(UserSettingsRepository.class); private final DailyStatusService status=mock(DailyStatusService.class); private final PendingNutritionQuoteRepository quotes=mock(PendingNutritionQuoteRepository.class); private final NutritionSourceCacheRepository cache=mock(NutritionSourceCacheRepository.class); private final FoodUser user=new FoodUser(1,"Vlad"); private JournalToolExecutor executor;
  @BeforeEach void setUp(){UserSettings profile=new UserSettings(user,"Europe/Bucharest");when(settings.findById(any())).thenReturn(Optional.of(profile));when(entries.findByUserAndEatenAtBetweenOrderByEatenAtAsc(any(),any(),any())).thenReturn(List.of());FoodEntry saved=mock(FoodEntry.class);when(saved.getId()).thenReturn(9L);when(saved.getCalories()).thenReturn(125);when(saved.getEatenAt()).thenReturn(Instant.EPOCH);when(saved.getOriginalMessage()).thenReturn("50g crenvusti");when(entries.save(any())).thenReturn(saved);when(quotes.save(any())).thenAnswer(i->i.getArgument(0));NutritionResolver resolver=(u,i)->new NutritionResolver.ResolvedMealItem(new JournalIntent.MealItem(i.name(),i.grams(),i.caloriesPer100g()==null?i.totalCalories():(int)Math.round(i.grams()*i.caloriesPer100g()/100d),i.caloriesPer100g(),null,null,null,i.barcode()),"manual");executor=new JournalToolExecutor(new ObjectMapper(),settings,entries,items,mock(PrivateFoodRepository.class),resolver,status,mock(PendingAgentActionRepository.class),null,quotes,cache);}
  @Test void estimateCreatesOwnerBoundQuoteWithoutWriting(){AgentToolResult result=execute("estimate_food","{\"name\":\"crenvusti\",\"grams\":50,\"caloriesPer100g\":250}");assertThat(result.ok()).isTrue();assertThat(result.data()).containsKey("quoteId");ArgumentCaptor<PendingNutritionQuote> quote=ArgumentCaptor.forClass(PendingNutritionQuote.class);verify(quotes).save(quote.capture());assertThat(quote.getValue().getType()).isEqualTo(PendingNutritionQuote.Type.AI_ESTIMATE);assertThat(quote.getValue().getCaloriesPer100g()).isEqualTo(250);verifyNoInteractions(entries,items,status);}
  @Test void forgedPackagedValuesCannotCreateAnEntry(){AgentToolResult result=execute("create_food_entry","{\"items\":[{\"nutritionMode\":\"PACKAGED_MATCH\",\"quoteId\":\"00000000-0000-0000-0000-000000000001\",\"name\":\"forged\",\"grams\":50,\"caloriesPer100g\":9999,\"barcode\":\"12345678\"}]}");assertThat(result.code()).isEqualTo("NOT_FOUND");verifyNoInteractions(entries,items,status);}
  @Test void forgedAiEstimateCannotCreateAnEntry(){AgentToolResult result=execute("create_food_entry","{\"items\":[{\"nutritionMode\":\"AI_ESTIMATE\",\"quoteId\":\"00000000-0000-0000-0000-000000000002\",\"name\":\"forged\",\"grams\":50,\"caloriesPer100g\":250}]}");assertThat(result.code()).isEqualTo("NOT_FOUND");verifyNoInteractions(entries,items,status);}
  @Test void packagedQuoteIsConsumedCachedAndItsServerValuesWin(){PendingNutritionQuote quote=PendingNutritionQuote.packaged(user,UUID.randomUUID(),"Crenvusti","Brand",50,250,"12345678","https://off.test/p",Instant.now());when(quotes.lockOwnedActive(eq(quote.getId()),eq(user),any())).thenReturn(Optional.of(quote));when(cache.findByBarcode("12345678")).thenReturn(Optional.empty());AgentToolResult result=execute("create_food_entry",String.format("{\"items\":[{\"nutritionMode\":\"PACKAGED_MATCH\",\"quoteId\":\"%s\",\"name\":\"forged\",\"grams\":1,\"caloriesPer100g\":9999}]}",quote.getId()));assertThat(result.ok()).isTrue();ArgumentCaptor<FoodEntry> entry=ArgumentCaptor.forClass(FoodEntry.class);verify(entries).save(entry.capture());assertThat(entry.getValue().getCalories()).isEqualTo(125);assertThat(entry.getValue().getNutritionSource()).isEqualTo("open_food_facts_estimate");verify(cache).save(any(NutritionSourceCache.class));verify(quotes).delete(quote);}
  @Test void sameQuoteTwiceInOneMealIsRejectedBeforeAnyWrite(){PendingNutritionQuote quote=PendingNutritionQuote.packaged(user,UUID.randomUUID(),"Crenvusti","Brand",50,250,"12345678","https://off.test/p",Instant.now());String row="{\"nutritionMode\":\"PACKAGED_MATCH\",\"quoteId\":\""+quote.getId()+"\"}";AgentToolResult result=execute("create_food_entry","{\"items\":["+row+","+row+"]}");assertThat(result.code()).isEqualTo("VALIDATION_ERROR");verifyNoInteractions(entries,items,status);}
  @Test void declaredNutritionRemainsManualAndHighConfidence(){AgentToolResult result=execute("create_food_entry","{\"items\":[{\"nutritionMode\":\"DECLARED\",\"name\":\"crispy\",\"grams\":165,\"caloriesPer100g\":229}]}");assertThat(result.ok()).isTrue();ArgumentCaptor<FoodEntry> entry=ArgumentCaptor.forClass(FoodEntry.class);verify(entries).save(entry.capture());assertThat(entry.getValue().getNutritionSource()).isEqualTo("manual");assertThat(entry.getValue().getConfidence()).isEqualTo("high");}
  private AgentToolResult execute(String name,String arguments){return executor.execute(new AgentContext(user,1,true,"50g crenvusti",Instant.now()),new JournalAgentModel.ToolCall("call",name,arguments),new ArrayList<>());}
}
