package io.github.foodjournal.messaging;

import com.fasterxml.jackson.databind.*; import io.github.foodjournal.config.MessagingProperties; import java.net.URI; import java.net.http.*; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicBoolean; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.SmartLifecycle; import org.springframework.stereotype.Component;

/** Maintains the authenticated Mattermost event stream. Reconnects are safe because inbox keys are durable. */
@Component @ConditionalOnProperty(prefix="food-journal.frontends.mattermost",name="enabled",havingValue="true")
public class MattermostWebSocketListener implements SmartLifecycle {
 private final MessagingProperties.Mattermost config; private final MessagingIngressService ingress; private final ObjectMapper json; private final MattermostFrontend frontend; private final HttpClient client=HttpClient.newHttpClient(); private final ScheduledExecutorService reconnect=Executors.newSingleThreadScheduledExecutor(); private final AtomicBoolean running=new AtomicBoolean(); private volatile WebSocket socket;
 public MattermostWebSocketListener(MessagingProperties properties,MessagingIngressService ingress,ObjectMapper json,MattermostFrontend frontend){this.config=properties.mattermost();this.ingress=ingress;this.json=json;this.frontend=frontend;}
 public void start(){if(running.compareAndSet(false,true))connect();} public void stop(){running.set(false);if(socket!=null)socket.sendClose(WebSocket.NORMAL_CLOSURE,"shutdown");reconnect.shutdownNow();} public boolean isRunning(){return running.get();} public boolean isAutoStartup(){return true;} public int getPhase(){return 0;}
 private void connect(){if(!running.get())return;try{String url=config.internalUrl().replaceFirst("^http","ws")+"/api/v4/websocket";client.newWebSocketBuilder().header("Authorization","Bearer "+config.botToken()).buildAsync(URI.create(url),new Listener()).whenComplete((opened,error)->{if(error!=null)schedule();else socket=opened;});}catch(RuntimeException failure){schedule();}}
 private void schedule(){if(running.get()&&!reconnect.isShutdown())reconnect.schedule(this::connect,5,TimeUnit.SECONDS);}
 private void posted(JsonNode frame){try{JsonNode data=frame.path("data");JsonNode post=json.readTree(data.path("post").asText("{}"));String user=post.path("user_id").asText();if(user.isBlank()||user.equals(config.botUserId())||!config.allowedUserIds().contains(user))return;if(!"D".equals(data.path("channel_type").asText()))return;List<Attachment> files=new ArrayList<>();for(JsonNode id:post.path("file_ids")){String fileId=id.asText();if(!fileId.isBlank())files.add(frontend.attachment(fileId));}String event=post.path("id").asText();String channel=post.path("channel_id").asText();if(event.isBlank()||channel.isBlank())return;ingress.accept(new InboundMessage("mattermost",event,user,channel,data.path("sender_name").asText("Member"),null,post.path("message").asText(null),null,files));}catch(Exception ignored){/* malformed third-party event is not journal input */}}
 private final class Listener implements WebSocket.Listener { private final StringBuilder text=new StringBuilder(); public CompletionStage<?> onText(WebSocket ws,CharSequence data,boolean last){text.append(data);if(last){try{JsonNode frame=json.readTree(text.toString());if("posted".equals(frame.path("event").asText()))posted(frame);}catch(Exception ignored){}finally{text.setLength(0);}}ws.request(1);return CompletableFuture.completedFuture(null);} public void onOpen(WebSocket ws){ws.request(1);} public CompletionStage<?> onClose(WebSocket ws,int status,String reason){schedule();return CompletableFuture.completedFuture(null);} public void onError(WebSocket ws,Throwable error){schedule();} }
}
