"""Verifies every SQLAlchemy model matches the real (Flyway-created) schema by
reflecting the live database and diffing column names, and by round-tripping
one row per aggregate through the ORM. Run against a Postgres instance that
was seeded by replaying the actual V1-V17 Flyway SQL files (see python-app
Phase 1 notes) -- not a schema generated by Base.metadata.create_all."""

import uuid
from datetime import UTC, datetime, timedelta

import pytest
from sqlalchemy import inspect, select

from app.db.base import Base, get_engine, get_session_factory
from app.db.models.conversation import ConversationMemory
from app.db.models.entries import FoodEntry, FoodItem
from app.db.models.journal_changes import JournalChangeMutation, JournalChangeSet
from app.db.models.messaging import (
    FrontendLinkCode,
    MessagingDailyStatus,
    MessagingIdentity,
    MessagingInboxMessage,
    MessagingOutboundMessage,
    MessagingRoute,
    PinnedDailyStatus,
)
from app.db.models.nutrition import (
    NutritionSourceCache,
    PendingNutritionQuote,
    PrivateFood,
)
from app.db.models.reports import ReportDelivery
from app.db.models.users import FoodUser, UserSettings


@pytest.mark.asyncio
async def test_every_model_column_exists_in_the_real_schema():
    engine = get_engine()
    async with engine.connect() as conn:

        def _reflect(sync_conn):
            inspector = inspect(sync_conn)
            return {t: {c["name"] for c in inspector.get_columns(t)} for t in inspector.get_table_names()}

        real_columns = await conn.run_sync(_reflect)

    mismatches = []
    for table in Base.metadata.tables.values():
        if table.name not in real_columns:
            mismatches.append(f"table {table.name} missing from real schema")
            continue
        model_cols = {c.name for c in table.columns}
        missing_in_db = model_cols - real_columns[table.name]
        if missing_in_db:
            mismatches.append(f"{table.name}: columns in model but not in DB: {missing_in_db}")

    assert not mismatches, "\n".join(mismatches)


@pytest.mark.asyncio
async def test_full_round_trip_through_every_aggregate():
    now = datetime.now(UTC)
    Session = get_session_factory()
    async with Session() as session:
        user = FoodUser(telegram_user_id=999000111, display_name="Schema Check", created_at=now)
        session.add(user)
        await session.flush()

        settings = UserSettings(user_id=user.id, timezone="Europe/Bucharest")
        session.add(settings)

        entry = FoodEntry(
            user_id=user.id,
            original_message="test entry",
            eaten_at=now,
            calories=500,
            nutrition_source="manual",
            confidence="high",
            created_at=now,
        )
        session.add(entry)
        await session.flush()

        item = FoodItem(entry_id=entry.id, name="test item", quantity=100, quantity_unit="g", calories=500)
        session.add(item)

        private_food = PrivateFood(user_id=user.id, name="Test Soup", calories_per_100g=80, created_at=now)
        session.add(private_food)

        cache = NutritionSourceCache(
            barcode="12345678", product_name="Test Product", calories_per_100g=200, source_url="https://example.com", fetched_at=now
        )
        session.add(cache)

        quote = PendingNutritionQuote(
            quote_id=uuid.uuid4(),
            batch_id=uuid.uuid4(),
            user_id=user.id,
            quote_type="AI_ESTIMATE",
            product_name="Estimated food",
            grams=100,
            calories_per_100g=150,
            created_at=now,
            expires_at=now + timedelta(minutes=30),
        )
        session.add(quote)

        change_set = JournalChangeSet(user_id=user.id, created_at=now, expires_at=now + timedelta(minutes=10))
        session.add(change_set)
        await session.flush()
        mutation = JournalChangeMutation(
            change_set_id=change_set.id,
            sequence_number=0,
            action_type="CREATE",
            after_state={"entryId": entry.id, "originalMessage": "x", "eatenAt": now.isoformat(), "calories": 500,
                          "nutritionSource": "manual", "confidence": "high", "deletedAt": None, "items": []},
        )
        session.add(mutation)

        identity = MessagingIdentity(user_id=user.id, provider="telegram", external_user_id=str(user.telegram_user_id))
        session.add(identity)
        route = MessagingRoute(user_id=user.id, provider="telegram", conversation_id=str(user.telegram_user_id))
        session.add(route)
        link_code = FrontendLinkCode(code="ABCD1234", user_id=user.id, expires_at=now + timedelta(minutes=10))
        session.add(link_code)

        inbox = MessagingInboxMessage(provider="telegram", event_id=str(uuid.uuid4()), payload="{}", next_attempt_at=now)
        session.add(inbox)
        outbox = MessagingOutboundMessage(provider="telegram", conversation_id="1", text="hi", next_attempt_at=now)
        session.add(outbox)

        daily_status = MessagingDailyStatus(user_id=user.id, provider="telegram", conversation_id="1", text="today")
        session.add(daily_status)
        pinned = PinnedDailyStatus(
            user_id=user.id,
            chat_id=1,
            local_date=datetime.now(UTC).date(),
            desired_text="pinned",
            desired_version=1,
            delivered_version=0,
            updated_at=now,
        )
        session.add(pinned)

        report = ReportDelivery(user_id=user.id, report_type="morning", local_date=datetime.now(UTC).date(), delivered_at=now)
        session.add(report)

        memory = ConversationMemory(user_id=user.id, role="user", content="hi", created_at=now)
        session.add(memory)

        await session.commit()

        # Round-trip the state-machine methods on the two queue tables.
        inbox.claim()
        await session.flush()
        assert inbox.status == "IN_PROGRESS"
        inbox.retry(inbox.lease_token)
        await session.commit()
        assert inbox.status == "PENDING"

        outbox.claim()
        await session.flush()
        outbox.retry()
        await session.commit()
        assert outbox.status == "PENDING"
        assert outbox.attempts == 1

        pinned.claim()
        await session.flush()
        pinned.retry(pinned.lease_token)
        await session.commit()
        assert pinned.delivered_version < pinned.desired_version
        assert pinned.status == "RETRY_1"

        loaded_user = (await session.execute(select(FoodUser).where(FoodUser.id == user.id))).scalar_one()
        assert loaded_user.display_name == "Schema Check"
