package io.github.foodjournal.service;
import io.github.foodjournal.config.BotProperties; import io.github.foodjournal.domain.*; import io.github.foodjournal.repository.*; import io.github.foodjournal.telegram.*; import io.github.foodjournal.application.*; import java.util.Comparator; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class UpdateService {
 private final BotProperties props; private final ProcessedTelegramUpdateRepository processed; private final OutboundTelegramMessageRepository outbound; private final JournalApplicationService journal; private final VoiceTranscriber voice; private final FoodMediaExtractor media; private final FoodUserRepository users; private final ConversationMemoryService memory; private final AgentRunRepository agentRuns; private final io.github.foodjournal.application.observability.AgentRunRequestContext traceContext;
 @Autowired public UpdateService(BotProperties p,ProcessedTelegramUpdateRepository d,OutboundTelegramMessageRepository o,JournalApplicationService j,VoiceTranscriber v,FoodMediaExtractor m,FoodUserRepository users,ConversationMemoryService memory,AgentRunRepository agentRuns,io.github.foodjournal.application.observability.AgentRunRequestContext traceContext){props=p;processed=d;outbound=o;journal=j;voice=v;media=m;this.users=users;this.memory=memory;this.agentRuns=agentRuns;this.traceContext=traceContext;}
 public UpdateService(BotProperties p,ProcessedTelegramUpdateRepository d,OutboundTelegramMessageRepository o,JournalApplicationService j,VoiceTranscriber v,FoodMediaExtractor m){this(p,d,o,j,v,m,null,null,null,null);}
 public UpdateService(BotProperties p,ProcessedTelegramUpdateRepository d,OutboundTelegramMessageRepository o,JournalApplicationService j,VoiceTranscriber v){this(p,d,o,j,v,(file,mime,type)->{throw new IllegalStateException("Media analysis unavailable");},null,null,null,null);}
 @Transactional public void handle(TelegramUpdate update){
   if(update==null || update.update_id()==null) return;
   TelegramMessage msg=update.message()!=null?update.message():update.edited_message(); if(msg==null||msg.from()==null||msg.from().id()==null||msg.chat()==null||msg.chat().id()==null) return;
   long id=msg.from().id(); if(!props.allowedTelegramUserIds().contains(id)) return;
   if(processed.claimIfNew(update.update_id()) == 0) return;
   String text=msg.text(); if((text==null||text.isBlank())&&msg.voice()!=null){try{text=voice.transcribe(msg.voice().file_id(),msg.voice().mime_type());}catch(Exception failure){outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I could not transcribe that voice note. Please try again or send text."));return;}} if((text==null||text.isBlank())&&msg.photo()!=null&&!msg.photo().isEmpty()){try{TelegramPhoto photo=msg.photo().stream().filter(p->p!=null&&p.file_id()!=null&&!p.file_id().isBlank()).max(Comparator.comparing(p->p.file_size()==null?0:p.file_size())).orElseThrow();text=withCaption(media.extract(photo.file_id(),"image/jpeg",FoodMediaType.PHOTO),msg.caption());}catch(Exception failure){outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I could not analyze that photo. Please send a clearer food photo or text."));return;}} if((text==null||text.isBlank())&&msg.document()!=null){try{text=withCaption(media.extract(msg.document().file_id(),msg.document().mime_type(),FoodMediaType.DOCUMENT),msg.caption());}catch(Exception failure){outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I could not analyze that document. Please send a PDF with a food label or use text."));return;}} if(text==null||text.isBlank()){ outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I received your media. No original file was stored.")); return; }
   String input=text.trim(); if(traceContext!=null)traceContext.begin(update.update_id(),msg.voice()!=null?"VOICE":(msg.photo()!=null&&!msg.photo().isEmpty()?"PHOTO":(msg.document()!=null?"DOCUMENT":"TEXT"))); try {String reply=(msg.photo()!=null&&!msg.photo().isEmpty()||msg.document()!=null)?journal.handleMediaEvidence(id,msg.chat().id(),msg.from().first_name(),input):journal.handle(id,msg.chat().id(),msg.from().first_name(),input); java.util.UUID runId=traceContext==null||traceContext.current()==null?null:traceContext.current().runId(); io.github.foodjournal.domain.AgentRun run=runId==null||agentRuns==null?null:agentRuns.findById(runId).orElse(null); outbound.save(new OutboundTelegramMessage(msg.chat().id(),reply,run)); if(memory!=null&&users!=null)users.findByTelegramUserId(id).ifPresent(user->memory.recordTurn(user,input,reply));} finally {if(traceContext!=null)traceContext.clear();}
 }
 private String withCaption(String extraction,String caption){return caption==null||caption.isBlank()?extraction:extraction+"\nUser caption: "+caption.trim();}
}
