package io.github.foodjournal.service;
import io.github.foodjournal.config.BotProperties; import io.github.foodjournal.domain.OutboundTelegramMessage; import io.github.foodjournal.repository.ProcessedTelegramUpdateRepository; import io.github.foodjournal.repository.OutboundTelegramMessageRepository; import io.github.foodjournal.telegram.*; import io.github.foodjournal.application.*; import java.util.Comparator; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class UpdateService {
 private final BotProperties props; private final ProcessedTelegramUpdateRepository processed; private final OutboundTelegramMessageRepository outbound; private final JournalApplicationService journal; private final VoiceTranscriber voice; private final FoodMediaExtractor media;
 @Autowired public UpdateService(BotProperties p,ProcessedTelegramUpdateRepository d,OutboundTelegramMessageRepository o,JournalApplicationService j,VoiceTranscriber v,FoodMediaExtractor m){props=p;processed=d;outbound=o;journal=j;voice=v;media=m;}
 public UpdateService(BotProperties p,ProcessedTelegramUpdateRepository d,OutboundTelegramMessageRepository o,JournalApplicationService j,VoiceTranscriber v){this(p,d,o,j,v,(file,mime,type)->{throw new IllegalStateException("Media analysis unavailable");});}
 @Transactional public void handle(TelegramUpdate update){
   if(update==null || update.update_id()==null) return;
   TelegramMessage msg=update.message()!=null?update.message():update.edited_message(); if(msg==null||msg.from()==null||msg.from().id()==null||msg.chat()==null||msg.chat().id()==null) return;
   long id=msg.from().id(); if(!props.allowedTelegramUserIds().contains(id)) return;
   if(processed.claimIfNew(update.update_id()) == 0) return;
   String text=msg.text(); if((text==null||text.isBlank())&&msg.voice()!=null){try{text=voice.transcribe(msg.voice().file_id(),msg.voice().mime_type());}catch(Exception failure){outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I could not transcribe that voice note. Please try again or send text."));return;}} if((text==null||text.isBlank())&&msg.photo()!=null&&!msg.photo().isEmpty()){try{TelegramPhoto photo=msg.photo().stream().filter(p->p!=null&&p.file_id()!=null&&!p.file_id().isBlank()).max(Comparator.comparing(p->p.file_size()==null?0:p.file_size())).orElseThrow();text=withCaption(media.extract(photo.file_id(),"image/jpeg",FoodMediaType.PHOTO),msg.caption());}catch(Exception failure){outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I could not analyze that photo. Please send a clearer food photo or text."));return;}} if((text==null||text.isBlank())&&msg.document()!=null){try{text=withCaption(media.extract(msg.document().file_id(),msg.document().mime_type(),FoodMediaType.DOCUMENT),msg.caption());}catch(Exception failure){outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I could not analyze that document. Please send a PDF with a food label or use text."));return;}} if(text==null||text.isBlank()){ outbound.save(new OutboundTelegramMessage(msg.chat().id(),"I received your media. No original file was stored.")); return; }
   String reply=(msg.photo()!=null&&!msg.photo().isEmpty()||msg.document()!=null)?journal.handleMediaEvidence(id,msg.chat().id(),msg.from().first_name(),text.trim()):journal.handle(id,msg.chat().id(),msg.from().first_name(),text.trim()); outbound.save(new OutboundTelegramMessage(msg.chat().id(),reply));
 }
 private String withCaption(String extraction,String caption){return caption==null||caption.isBlank()?extraction:extraction+"\nUser caption: "+caption.trim();}
}
